import { Document, Page, View, Text } from "@react-pdf/renderer";
import { PdfSection } from "../components/PdfSection";
import { PdfQuestionBlock } from "../components/PdfQuestionBlock";
import { documentStyles } from "../document-styles";
import type { Question } from "@/types/interview";

interface QuestionPdfDocProps {
  questions: Question[];
  title?: string;
}

export function QuestionPdfDoc({
  questions,
  title = "My Questions & Answers",
}: QuestionPdfDocProps) {
  return (
    <Document title={title}>
      <Page size="A4" style={documentStyles.page}>
        <View style={documentStyles.pageHeader}>
          <Text style={documentStyles.docTitle}>{title}</Text>
          <Text style={documentStyles.docSubtitle}>
            {questions.length} question{questions.length !== 1 ? "s" : ""} • Generated by Prepify
          </Text>
        </View>
        <PdfSection title="Questions & answers">
          {questions.map((q, index) => (
            <PdfQuestionBlock
              key={q.id}
              question={q}
              index={index}
              showRating={true}
              showFeedback={true}
            />
          ))}
        </PdfSection>
        <Text style={documentStyles.footer}>
          Prepify — AI Mock Interview Practice • {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
